memodir = "~/memo/_posts"
editor = "vim"
column = 20
width = 0
selectcmd = "peco"
grepcmd = "grep -nH --color=always ${PATTERN} ${FILES} | less -R"
memotemplate = ""
assetsdir = "."
pluginsdir = "~/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
