[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = '907th/vim-auto-save'

[[plugins]]
repo = 'mattn/vim-molder'
